name: 'Checks'
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Restore yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Grant read access to private registry
        run: yarn config set --home 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"
      - name: Install dependencies
        run: yarn --immutable
      - name: Format
        run: yarn format:check
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Checked in build?
        run: git diff --exit-code
      - name: Lint
        run: yarn lint
